### ISSUE TITLE
Cannot run SAGA using GAMA model

### ISSUE THREAD

**Issue by weifengsd** [NoiseLabUCSD/saga5.5#2]
Hello!
 I have found there there is very few information about GAMA model in SAGA.  
The example also cannot work well, the errors are the number of receiver depths and ranges must be integer. 
Could you please offer more explanations on the meanings of parameters?
Thanks!
Wei Feng

**Comment by NoiseLabUCSD** [comment]
Hi Wei Feng,

Thanks for your valuable feedback about SAGA. I’ve looked at GAMA model in SAGA and made some updates to solve the issues you mentioned. 

1. The error ' the number of receiver depths and ranges must be integer ‘ was caused by the number format of input file(i.e., *.dat). In the input file, the number of receiver depths and ranges should be written as integer format, for example ‘ 1 ‘ instead of ‘1.0000’ , and ‘-128’ instead of ‘-128.00’. You can revise this in your input file or download the updated input file from Github.

2. And I also found some additional issues on GAMA model in SAGA. So some updates were made. Here are the updated files:

	saga/src/Makefile      (some compiler options were added for GAMA model)
	saga/src/gama/mem_lim.f   
	saga/src/gama/common/parms_conv
	saga/examples/gama/map2k_phla2000067091700.dat

   You can download the separate files above or the whole folder saga/src, then re-compile. I have tested this GAMA example and it works on my iMac (gfortran as compiler).

3. About the meanings of parameters. You can refer to SAGA manual and GAMA model manual which can be found from 'saga/doc/saga.pdf' and 'saga/doc/gama.guide.pdf'. The second one may be what you are looking for. It’s more detailed on GAMA model.

If you have any other questions, please feel free to provide feedback.

Thanks,

Haiqiang Niu

**Comment by weifengsd** [comment]
Hi Haiqiang Niu,

Thanks for your help, this issue is solved perfectly.

There is another problem in OAST model when running the examples. The error occurs when calling function WRITEoasTRF. The parameter of filename is not calculated correctly at line 481 of file oasgvms11.f. 
![oast](https://cloud.githubusercontent.com/assets/8778355/18700350/607a5f72-8009-11e6-850e-8cb7c04ee220.png)

Wish to hear from you!

Wei Feng

**Comment by NoiseLabUCSD** [comment]
Hi Wei Feng,

Thanks for your information. Actually by using ’saga layer11 oast’, it does finish the inversion and you can get the right inversion results too.

The problem you found is that some output file with optimal environment needs to be written out. This module doesn’t work for OAST model yet. So ’This is not yet working’ occurs. It’s not a bug and you can use it directly or just comment it out.

Haiqiang

On Sep 20, 2016, at 11:41 PM, weifengsd <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Haiqiang Niu,

Thanks for your help, this issue is solved perfectly.

There is another problem in OAST model when running the examples. The error occurs when calling function WRITEoasTRF. The parameter of filename is not calculated correctly at line 481 of file oasgvms11.f.
[oast]<https://cloud.githubusercontent.com/assets/8778355/18700350/607a5f72-8009-11e6-850e-8cb7c04ee220.png>

Wish to hear from you!

Wei Feng

**Comment by weifengsd** [comment]
Thanks for your reply, and I will close this issue.
Best wishes!

Wei Feng
